# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb50f48ad58853947108dc84da26e9b5c08882cb173418ca81cb8c2f0d67739282f4cd50ab193f04cfc8f2300a2bae1404518813fe770f517b71ab4bd5bc8ca

test:
  secret_key_base: 3749e9b5c2c8d3a2833103e19fb8fc750244556973034151a718b6429b61295e6880fdeece3ca82e0e6820d81a8170edd451e838306c3c7757fc49f9cafc7787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
